name: ens_normalize
description: Ethereum Name Service (ENS) Name Normalizer based on adraffy/ens-normalize.js.
version: 1.0.0
repository: https://github.com/vaariance/ens-dart

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  unorm_dart: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.0.0
