name: ens_normalize
description: Ethereum Name Service (ENS) Name Normalizer adapted from namehash labs and adraffy.
version: 1.0.1
repository: https://github.com/vaariance/ens-dart

environment:
  sdk: ^3.2.0

dependencies:
  unorm_dart: ^0.3.0
  tuple: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
